import { esc } from './utils.js';

/** Centralized category list — keep in sync with index.html <select#edit-category>. */
export const CATEGORIES = [
  { value: '餐飲', emoji: '🍽', label: '🍽 餐飲' },
  { value: '交通', emoji: '🚌', label: '🚌 交通' },
  { value: '購物', emoji: '🛍', label: '🛍 購物' },
  { value: '娛樂', emoji: '🎉', label: '🎉 娛樂' },
  { value: '生活', emoji: '🏠', label: '🏠 生活' },
  { value: '其他', emoji: '📦', label: '📦 其他' },
];

export const CATEGORY_STYLE = {
  餐飲: 'background:#fef3c7;color:#92400e',
  交通: 'background:#dbeafe;color:#1e40af',
  購物: 'background:#ede9fe;color:#5b21b6',
  娛樂: 'background:#fce7f3;color:#9d174d',
  生活: 'background:#d1fae5;color:#065f46',
  其他: 'background:#f3f4f6;color:#4b5563',
};

export const CATEGORY_KEYWORDS = {
  餐飲: [
    '餐',
    '飯',
    '食',
    '吃',
    '喝',
    '咖啡',
    '飲料',
    '早餐',
    '午餐',
    '晚餐',
    '宵夜',
    '麵',
    '粥',
    '鍋',
    '燒烤',
    '火鍋',
    '茶',
    '奶茶',
    '甜點',
    '蛋糕',
    '麵包',
    '便當',
    '小吃',
    '拉麵',
    '壽司',
    '漢堡',
    'pizza',
    '咖哩',
    '炒飯',
    '湯',
    '果汁',
    '牛奶',
    '豆漿',
    '河粉',
    '牛排',
    '炸雞',
    '滷肉',
    '燙',
    '沙拉',
    '三明治',
    '點心',
  ],
  交通: [
    '車',
    '捷運',
    '公車',
    '計程車',
    'uber',
    'taxi',
    '高鐵',
    '火車',
    '飛機',
    '機票',
    '油費',
    '加油',
    '停車',
    '過路費',
    '腳踏車',
    '機車',
    '租車',
    '轉運',
    '船',
    '渡輪',
  ],
  購物: [
    '購物',
    '超市',
    '賣場',
    '百貨',
    'costco',
    '全聯',
    '家樂福',
    '衣服',
    '鞋',
    '包',
    '3c',
    '電器',
    '書',
    '文具',
    '玩具',
    '禮物',
    '藥',
    '藥妝',
    '化妝',
    '保養',
    '日用',
    '雜貨',
    '家用',
    '清潔用',
  ],
  娛樂: [
    '電影',
    'ktv',
    '唱歌',
    '遊樂',
    '門票',
    '展覽',
    '表演',
    '音樂會',
    '景點',
    '遊樂園',
    '遊戲',
    '娛樂',
    '酒吧',
    'live',
    '演唱會',
  ],
  生活: [
    '水費',
    '電費',
    '瓦斯',
    '房租',
    '房貸',
    '管理費',
    '清潔',
    '打掃',
    '衛生紙',
    '洗衣',
    '家具',
    '沙發',
    '床',
    '燈',
    '鎖',
    '網路',
    '電話費',
    '保險',
    '醫療',
    '看診',
    '健身',
    '剪髮',
    '美容',
  ],
};

export function guessCategoryFromItem(item) {
  if (!item) return '';
  const s = item.toLowerCase();
  for (const [cat, kws] of Object.entries(CATEGORY_KEYWORDS)) {
    if (kws.some(k => s.includes(k.toLowerCase()))) return cat;
  }
  return '';
}

export function categoryBadgeHTML(cat) {
  if (!cat) return '';
  const st = CATEGORY_STYLE[cat] || 'background:#f3f4f6;color:#4b5563';
  return `<span style="${st};font-size:10px;font-weight:600;padding:1px 7px;border-radius:99px;margin-left:4px;vertical-align:middle;white-space:nowrap">${esc(cat)}</span>`;
}
