import { createHash } from 'node:crypto';
import { cpSync, existsSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');

if (!existsSync(resolve(dist, 'index.html'))) {
  console.error('dist/index.html does not exist. Run vite build before prepare-dist.');
  process.exit(1);
}

function copyToDist(rel) {
  const src = resolve(root, rel);
  if (!existsSync(src)) return;
  cpSync(src, resolve(dist, rel), { recursive: true });
}

copyToDist('.nojekyll');
copyToDist('manifest.json');
copyToDist('icons');

const indexPath = resolve(dist, 'index.html');
const indexHtml = readFileSync(indexPath, 'utf8')
  .replace(/href="\/hukeep-accounts\/assets\/favicon-[^"]+\.svg"/, 'href="/hukeep-accounts/icons/favicon.svg"')
  .replace(
    /href="\/hukeep-accounts\/assets\/apple-touch-icon-[^"]+\.png"/,
    'href="/hukeep-accounts/icons/apple-touch-icon.png"',
  )
  .replace(/href="\/hukeep-accounts\/assets\/manifest-[^"]+\.json"/, 'href="/hukeep-accounts/manifest.json"');
writeFileSync(indexPath, indexHtml);

const assetsDir = resolve(dist, 'assets');
if (existsSync(assetsDir)) {
  for (const file of readdirSync(assetsDir)) {
    if (/^(apple-touch-icon|favicon|manifest)-/.test(file)) {
      rmSync(resolve(assetsDir, file));
    }
  }
}

function posixPath(path) {
  return path.split('\\').join('/');
}

function listFiles(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  return entries.flatMap(entry => {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) return listFiles(fullPath);
    return [fullPath];
  });
}

const cacheableFiles = listFiles(dist)
  .map(file => posixPath(relative(dist, file)))
  .filter(file => file !== 'sw.js')
  .filter(file => file !== 'version.json')
  .filter(file => !file.startsWith('.'))
  .sort();

const hash = createHash('sha256');
for (const file of cacheableFiles) {
  const fullPath = resolve(dist, file);
  const stats = statSync(fullPath);
  hash.update(file);
  hash.update(String(stats.size));
  hash.update(readFileSync(fullPath));
}

const cacheName = `ledger-vite-${hash.digest('hex').slice(0, 12)}`;
const builtAt = new Date().toISOString();
const buildId = process.env.VITE_LEDGER_BUILD_ID || process.env.GITHUB_SHA || 'local';
writeFileSync(
  resolve(dist, 'version.json'),
  JSON.stringify(
    {
      buildId,
      builtAt,
      cacheName,
      base: '/hukeep-accounts/',
    },
    null,
    2,
  ),
);

const staticAssets = Array.from(new Set(['./', './index.html', ...cacheableFiles.map(file => `./${file}`), './version.json']));

const sw = `// Generated by scripts/prepare-dist.mjs. Do not edit dist/sw.js directly.
const CACHE_NAME = '${cacheName}';

const STATIC_ASSETS = ${JSON.stringify(staticAssets, null, 2)};

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(STATIC_ASSETS)),
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches
      .keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))),
  );
  self.clients.claim();
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);

  if (url.origin !== self.location.origin) return;
  if (event.request.method !== 'GET') return;

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then(response => {
          if (response.ok) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
          }
          return response;
        })
        .catch(async () => (await caches.match(event.request)) || caches.match('./index.html')),
    );
    return;
  }

  if (url.pathname.endsWith('.js') || url.pathname.endsWith('.css')) {
    event.respondWith(
      fetch(event.request)
        .then(response => {
          if (response.ok) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
          }
          return response;
        })
        .catch(async () => caches.match(event.request)),
    );
    return;
  }

  event.respondWith(
    caches.match(event.request).then(cached => {
      const fetching = fetch(event.request)
        .then(response => {
          if (response.ok) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then(c => c.put(event.request, clone));
          }
          return response;
        })
        .catch(() => cached);
      return cached || fetching;
    }),
  );
});
`;

writeFileSync(resolve(dist, 'sw.js'), sw);
console.log(`Prepared dist assets and ${cacheName}.`);
